# Generated by Django 6.0.2 on 2026-02-21 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_jobvacancy_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopprofile',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
