# Generated by Django 6.0.2 on 2026-02-21 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_shopprofile_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobvacancy',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='job_images/'),
        ),
    ]
