# Generated by Django 6.0.2 on 2026-02-21 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_jobvacancy_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
