# Generated by Django 6.0.2 on 2026-02-21 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_user_mobile_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='owner_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
