# Generated by Django 6.0.2 on 2026-02-21 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_jobapplication_owner_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobvacancy',
            name='job_type',
            field=models.CharField(choices=[('FULL_TIME', 'Full-Time'), ('PART_TIME', 'Part-Time'), ('REMOTE', 'Remote'), ('ON_SITE', 'On-Site'), ('HYBRID', 'Hybrid'), ('CONTRACT', 'Contract')], default='FULL_TIME', max_length=50),
        ),
    ]
