# Generated by Django 5.2.5 on 2026-02-23 13:13

import jobs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_user_profile_photo_alter_jobapplication_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='cv',
            field=models.FileField(blank=True, null=True, storage=jobs.models.select_raw_storage, upload_to='cvs/'),
        ),
    ]
